In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel("Online Retail.xlsx")

In [28]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [29]:
df.shape

(541909, 8)

In [30]:
print("Rows: ",df.shape[0])
print("Column: ",df.shape[1])

Rows:  541909
Column:  8

In [31]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [33]:
missing = df.isnull().sum()

print(missing)

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [34]:
missing_report= pd.DataFrame({
    "missing values": df.isnull().sum(),
    "Percentage":(df.isnull().sum()/len(df) *100).round(2)
})
missing_report

             missing values  Percentage
InvoiceNo                 0        0.00
StockCode                 0        0.00
Description            1454        0.27
Quantity                  0        0.00
InvoiceDate               0        0.00
UnitPrice                 0        0.00
CustomerID           135080       24.93
Country                   0        0.00

In [35]:
duplicate_count=df.duplicated().sum()

print("Duplicate Count: ",duplicate_count)

Duplicate Count:  5268

In [36]:
df[df.duplicated()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [37]:
df["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [38]:
df["Country"].nunique()

38

In [39]:
df["Description"].head(20)

0      WHITE HANGING HEART T-LIGHT HOLDER
1                     WHITE METAL LANTERN
2          CREAM CUPID HEARTS COAT HANGER
3     KNITTED UNION FLAG HOT WATER BOTTLE
4          RED WOOLLY HOTTIE WHITE HEART.
5            SET 7 BABUSHKA NESTING BOXES
6       GLASS STAR FROSTED T-LIGHT HOLDER
7                  HAND WARMER UNION JACK
8               HAND WARMER RED POLKA DOT
9           ASSORTED COLOUR BIRD ORNAMENT
10             POPPY'S PLAYHOUSE BEDROOM
11              POPPY'S PLAYHOUSE KITCHEN
12      FELTCRAFT PRINCESS CHARLOTTE DOLL
13                IVORY KNITTED MUG COSY
14     BOX OF 6 ASSORTED COLOUR TEASPOONS
15          BOX OF VINTAGE JIGSAW BLOCKS
16         BOX OF VINTAGE ALPHABET BLOCKS
17               HOME BUILDING BLOCK WORD
18               LOVE BUILDING BLOCK WORD
19            RECIPE BOX WITH METAL HEART
Name: Description, dtype: object

In [40]:
df["StockCode"].head(20)

0     85123A
1      71053
2     84406B
3     84029G
4     84029E
5      22752
6      21730
7      22633
8      22632
9      84879
10     22745
11     22748
12     22749
13     22310
14     84969
15     22623
16     22622
17     21754
18     21755
19     21777
Name: StockCode, dtype: object

In [41]:
df["InvoiceNo"].head()

0    536365
1    536365
2    536365
3    536365
4    536365
Name: InvoiceNo, dtype: object

In [42]:
df["Quantity"].describe()

count    541909.000000
mean          9.552250
std         218.081158
min      -80995.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       80995.000000
Name: Quantity, dtype: float64

In [43]:
negative_quantity = df[df["Quantity"] <= 0]

print("Non-positive quantity:", len(negative_quantity))

Non-positive quantity: 10624

In [44]:
print("Minimum Quantity:", df["Quantity"].min())
print("Maximum Quantity:", df["Quantity"].max())

Minimum Quantity: -80995
Maximum Quantity: 80995

In [45]:
invalid_quantity = df[df["Quantity"] <= 0]

print("Quantity <= 0:", len(invalid_quantity))

Quantity <= 0: 10624

In [46]:
invalid_quantity.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [47]:
df["UnitPrice"].describe()

count    541909.000000
mean          4.611114
std          96.759853
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       38970.000000
Name: UnitPrice, dtype: float64

In [48]:
df["UnitPrice"].describe()

count    541909.000000
mean          4.611114
std          96.759853
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       38970.000000
Name: UnitPrice, dtype: float64

In [49]:
invalid_quantity.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [50]:
invalid_price = df[df["UnitPrice"] <= 0]

print("Non-positive prices:", len(invalid_price))

Non-positive prices: 2517

In [51]:
df_clean = df.copy()

In [52]:
df_clean = df_clean.drop_duplicates()

In [53]:
print("Rows after removing duplicates:", len(df_clean))

Rows after removing duplicates: 536641

In [54]:
text_columns = ["InvoiceNo", "StockCode", "Description", "Country"]

for col in text_columns:
    df_clean[col] = df_clean[col].astype("string").str.strip()

In [55]:
df_clean = df_clean.dropna(
    subset=["Description", "CustomerID"]
)

In [56]:
df_clean.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [57]:
df_clean = df_clean[df_clean["Quantity"] > 0]

In [58]:
print("Invalid quantities remaining:",
      (df_clean["Quantity"] <= 0).sum())

Invalid quantities remaining: 0

In [59]:
df_clean = df_clean[df_clean["UnitPrice"] > 0]

In [60]:
print("Invalid prices remaining:",
      (df_clean["UnitPrice"] <= 0).sum())

Invalid prices remaining: 0

In [64]:
df_clean["InvoiceNo"] = df_clean["InvoiceNo"].astype("string")
df_clean["StockCode"] = df_clean["StockCode"].astype("string")
df_clean["Description"] = df_clean["Description"].astype("string")
df_clean["Country"] = df_clean["Country"].astype("string")

In [65]:
df_clean["CustomerID"] = pd.to_numeric(
    df_clean["CustomerID"],
    errors="coerce"
).astype("Int64")

In [66]:
df_clean["Quantity"] = pd.to_numeric(
    df_clean["Quantity"],
    errors="coerce"
).astype("Int64")

In [67]:
df_clean["UnitPrice"] = pd.to_numeric(
    df_clean["UnitPrice"],
    errors="coerce"
)

In [68]:
df_clean["InvoiceDate"] = pd.to_datetime(
    df_clean["InvoiceDate"],
    errors="coerce"
)

In [69]:
df_clean["TotalAmount"] = (
    df_clean["Quantity"] * df_clean["UnitPrice"]
).round(2)

In [70]:
df_clean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.3
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [71]:
df_clean.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalAmount    0
dtype: int64

In [72]:
print(
    "Duplicate records:",
    df_clean.duplicated().sum()
)

Duplicate records: 0

In [73]:
print(
    "UnitPrice <= 0:",
    (df_clean["UnitPrice"] <= 0).sum()
)

UnitPrice <= 0: 0

In [74]:
print("Final rows:", len(df_clean))
print("Final columns:", len(df_clean.columns))

Final rows: 392692
Final columns: 9

In [75]:
df_clean.to_csv(
    "online_retail_cleaned.csv",
    index=False
)